from .resume_prompt import RESUME_ANALYSIS_PROMPT
from .job_prompt import JOB_ANALYSIS_PROMPT
from .match_prompt import MATCH_ANALYSIS_PROMPT
from .tailor_prompt import RESUME_TAILOR_PROMPT
from .cover_letter_prompt import COVER_LETTER_PROMPT